author: Torahime
name: Freecube
version: '${version}'
main: fr.torahime.freecube.Freecube
api-version: '1.20'
commands:
  fc:
    description: main fc command
    aliases:
      - FC

  tp:
    description: tp command
  msg:
    description: msg command
    aliases:
      - m
  r:
    description: respond command