author: Torahime
name: Freecube
version: '${version}'
main: fr.torahime.freecube.Freecube
api-version: '1.20'
commands:
  fc:
    description: main fc command
    permission: freecube.player.fc
  tp:
    description: tp command
    permission: freecube.player.tp
  msg:
    description: msg command
    permission: freecube.player.msg
    aliases:
      - m
  r:
    description: respond command
    permission: freecube.player.respond
